# Server Configuration
server:
  port: 5050
  contextPath:

security:
  basic:
    enabled: false

config:
  oauth2:
    clientId:client
    clientSecret:secret
    accessTokenUri:http://localhost:7090/oauth/token
    userAuthorizationUri:http://localhost:7090/oauth/authorize
    resourceUri:http://localhost:7090/api/

# Spring Configuration
#spring:
#  data:
#    mongodb:
#      uri: mongodb://139.196.148.7:27017/test
#  jackson:
#      serialization:
#        INDENT_OUTPUT: true

# Logging Configuration
logging:
  level:
    org.springframework:
      data:DEBUG
      sercurity:DEBUG